# Generated by Django 4.1.7 on 2023-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images', verbose_name='Личное фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('S', 'Связующий'), ('MB', 'Центральный блокирующий'), ('Li', 'Либеро'), ('WS', 'Доигровщик'), ('D', 'Диагональный'), ('PL', 'Игрок')], default='PL', max_length=25, verbose_name='Позиция'),
        ),
    ]
