# Generated by Django 4.1.7 on 2023-02-24 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
    ]
