# Generated by Django 4.1.7 on 2023-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images', verbose_name='Символ команды'),
        ),
    ]
