# Generated by Django 4.1.7 on 2023-02-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_teams_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='rating',
        ),
    ]
