# Generated by Django 4.1.7 on 2023-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20, unique=True, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(verbose_name='Дата начала мероприятия')),
                ('date_time_end', models.DateTimeField(verbose_name='Дата окончания мероприятия')),
                ('description', models.TextField(blank=True, default='Волейбол, «Муссон». Игроков: мин.12/мах.18.Стоимость: ~100 - 150 руб. ⚠У кого есть мяч 🏐, просьба взять с собой. ❗Записался и не пришёл? Бан на неделю', null=True, verbose_name='Доп. информация')),
                ('reservation', models.PositiveSmallIntegerField(blank=True, default=18, verbose_name='Количество свободных мест')),
                ('on_main', models.BooleanField(default=False, verbose_name='Опубликовать на главную страницу?')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регистрация на игру',
                'verbose_name_plural': 'Регистрации на игру',
            },
        ),
    ]
