# Generated by Django 4.1.7 on 2023-03-08 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reservation',
            field=models.PositiveSmallIntegerField(blank=True, default=18, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)], verbose_name='Количество свободных мест'),
        ),
    ]
